apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
         component: web
    spec:
      containers:
        - name: server
          image: halad/multiserver
          ports:
            - containerPort: 5000
          env:
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
              valueFrom: 
                secretKeyRef:
                  name: pgpassword 
                  key: PGPASSWORD